<a href="https://colab.research.google.com/github/PraveenPrabhat125/Python-for-Data-Analyst/blob/main/Python_for_data_analysis_loops_iterator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Control Flow

### If, Else and Elif

In [2]:
x = 10
y = 4
z= 3

if x < y:
  print("x is smaller then y")
elif x == y:
  print("x == y")
else:
    print("y is smaller then x")

y is smaller then x


# For Loops¶
For loops are a programming construct that let you go through each item in a sequence and then perform some operation on each one. For instance, you could use a for loop to go through all the values in a list, tuple, dictionary or series and check whether each conforms to some logical expression or print the value to the console.

Create a for loop using the following syntax:

In [5]:
my_seq = list(range(0, 101, 10))
my_seq

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [6]:
for num in my_seq:
  print(num + 1)

1
11
21
31
41
51
61
71
81
91
101


### continue
In each iteration of the loop, the variable "number" takes on the value of the next item in the sequence.

For loops support a few special keywords that help you control the flow of the loop: continue and break.

The continue keyword causes a for loop to skip the current iteration and go to the next one:

In [7]:
for num in my_seq:
  if(num > 50):
    continue
  else:
    print(num)

0
10
20
30
40
50


### Break
The "break" keyword halts the execution of a for loop entirely. Use break to "break out" of a loop:

In [8]:
for num in my_seq:
  if(num > 50):
    break
  else:
    print(num)

0
10
20
30
40
50


## While Loops
While loops are similar to for loops in that they allow you to execute code over and over again. For loops execute their contents, at most, a number of iterations equal to the length of the sequence you are looping over. While loops, on the other hand, keep executing their contents as long as a logical expression you supply remains true:

In [9]:
x = 10
temp = 0

while(temp < x):
  print(temp)
  temp += 1


0
1
2
3
4
5
6
7
8
9


although you can use a while loop to do anything a for loop can do, it is best to use for loops whenever you want to perform a specific number of operations, such as when running some code on each item in a sequence. While loops should be reserved for cases where you don't know how many times you will need to execute a loop.

In [14]:
import numpy as np

m_d = np.random.uniform(-1, 1, 10)
m_d

m_d = np.random.random()
m_d

0.8360072849759508

## Random ()

In [22]:
r_num = np.random.random()
print(r_num)

# Generate a random integer between low (inclusive) and high (exclusive)
random_int = np.random.randint(1, 10)
print(random_int)

# Generate an array of random floats
r_array = np.random.random(size=(3,3,))
print(r_array)


# Generate an array of random floats
r_array = np.random.randint(1, 10 , size=(3,3,))
print(r_array)

0.4970448729401823
6
[[0.57530862 0.02770303 0.31649316]
 [0.11296508 0.97310617 0.69999875]
 [0.17711657 0.02058239 0.22632318]]
[[8 3 9]
 [5 7 6]
 [5 6 1]]


In [27]:
my_data = np.random.uniform(-1, 1, 25)

for index, num in  enumerate(my_data):
  print(index)
  if num < 0:
    my_data[index] = 0
print(my_data)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
[0.35291032 0.94543471 0.20333553 0.         0.4351275  0.
 0.         0.         0.38764103 0.         0.60389449 0.
 0.5642449  0.         0.         0.41929145 0.         0.
 0.         0.14859851 0.2563028  0.         0.         0.
 0.36835255]


## enumerate
Note: "enumerate" takes a sequence and turns it into a sequence of (index, value) tuples; enumerate() lets you loop over the items in a sequence while also having access the item's index.

Using a for loop to perform this sort of operation requires writing quite a bit of code and for loops are not particularly fast because they have to operate on each item in a sequence one at a time.

Numpy includes a function called where() that lets you perform an if/else check on a sequence with less code:

In [29]:
my_data = np.random.uniform(-1, 1, 25)

for index, num in my_data:
  print(index)
  if num < 0:
    my_data[index] = 0
print(my_data)

TypeError: cannot unpack non-iterable numpy.float64 object

In [35]:
new_data = np.random.uniform(-1,1,25)
new_data

array([ 0.49376583, -0.66804004,  0.93318265,  0.37262138, -0.95218781,
       -0.13456638, -0.10396252, -0.24211579, -0.50782279,  0.67005486,
        0.14861159, -0.18453567,  0.84178859, -0.06891479, -0.47829862,
        0.96291085,  0.50148666,  0.89129753, -0.4904988 , -0.4233368 ,
        0.85658516,  0.62903155,  0.68622406,  0.70710338,  0.63290792])

In [37]:
new_data1 = np.where(new_data < 0, 0, new_data)
new_data1

array([0.49376583, 0.        , 0.93318265, 0.37262138, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.67005486,
       0.14861159, 0.        , 0.84178859, 0.        , 0.        ,
       0.96291085, 0.50148666, 0.89129753, 0.        , 0.        ,
       0.85658516, 0.62903155, 0.68622406, 0.70710338, 0.63290792])